name: Resume Generator Workflow

on:
  workflow_dispatch:

jobs:
  generate-resume:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch resume from Gist
        run: |
          GIST_ID=$(curl -s "https://api.github.com/users/${GITHUB_REPOSITORY_OWNER}/gists" | jq -r '.[] | select(.files."resume.json" != null) | .id')
          if [ -z "$GIST_ID" ]; then
            exit 1
          fi

          curl -s "https://gist.githubusercontent.com/${GITHUB_REPOSITORY_OWNER}/${GIST_ID}/raw/resume.json" -o resume.json

      - name: Generate resume
        id: jsonresume-generator
        uses: Devleaps/jsonresume-generator@v1
        with:
          action: "render"
          file: "resume.json"
          output-type: "html"
          theme-local: "false"
          theme-name: "jsonresume-theme-stackoverflow"

      - name: Commit changes to gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update resume from Gist and regenerate HTML"
          git push
